---
title: "Flights Dataset"
subtitle: "Proposal"
author: 
  - name: "Lean Mean Learning Machines"
    affiliations:
      - name: "School of Information, University of Arizona"
description: "Project description"
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
jupyter: python3
---

```{python}
#| label: load-pkgs
#| message: false
import numpy as np
import pandas as pd
import seaborn as sns
```

## Introduction and data

```{python}
#| label: load-dataset
#| message: false

Flights_dt = pd.read_csv('data/flights.csv')
```

Make sure to load the data and use inline code for some of this information.

The source of the Dataset :

(https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-07-12)

The data was collected in Europe by the Air Traffic Flow Management (ATFM) which had required information in detail which was provided by The Europe ATC (Air Traffic Control). This data contains flight records for Belgian airports and our main objective is to explore flight patterns, trends, and relationships across different airports in Belgium.

## Research Question

-   How is the total number monthly flight departures ad arrivals at Brussels Airport comparatively to other major airports in Belgium, and what are the seasonal trends over the year ?

**Variables Included:**

`FLT_DEP_1`, `FLT_ARR_1,` `APT_NAME`, `MONTH_MON`

The Target Population for this study consists of flight details for major Belgian airports, with comparing Brussels Airport to other airports in the dataset.

**Importance of the question:**

This research question is important because the Brussels Airport is one of the most busiest Airport in Europe. So, the findings could assist airport management to plan ahead of the seasonal changes which could improve the Airports Efficeincy.

### Research Topic & Hypotheses

**Research Topic:**\
The study will analyze monthly total departures and arrivals at Brussels Airport and compare them with the other Airports in Belgium.

**Hypotheses:**

-   Hypothesis 1: Brussels Airport has consist high flight departures and arrival record compare to any other Belgian Airport in a year.

-   Hypothesis 2: Summer season shows the most increased activity on the Brussel Airport.

**Types of variables:**

-   Quantative Variables:

    `FLT_DEP_1` - Contains Total number of departing flights

    `FLT_ARR_1` - Contains Total number of arriving flights

-   Categorial Variables:

    `APT_NAME` - Conatins Airport names

    `MONTH_MON` - Conatins Month names

## Glimpse of data

```{python}
Flights_dt.head()
```

```{python}
Flights_dt.info()
```

## Analysis plan

**Data Exploration:**

1.  Initial Exploration:

    -   Use `.head()` to display first few rows of the dataset.

    -   Use `.info()` to check the data types of each column and any null column values.

**Variable Preprocessing:**

1.  Handling Missing Values:
    -   Filtering out the missing values in key columns to ensure the data consistency during analysis.
2.  Data Type Conversion:
    -   Ensuring the columns are in the desired format which is required if not convert them.

**Statistical Analysis:**

1.  Comparative Analysis by Airport:
    -   `APT_NAME` and `MONTH_MON` to calculate the summary statistics for flight departures and arrivals.

    -   Create a time series graphs for total departures `FLT_DEPT_1` and arrivals `FLT_ARR_1` to identify monthly and yearly trends at Brussels Airport compared to other Airports.
2.  Seasonal Analysis:
    -   Create bar plots and line graph to visualize seasonal trends in departures and arrivals , comparing different airports and months.

**Hypothesis Testing:**

-   Using Chi-Square Test or H - Test depending on the output.