---
title: "Car Recalls"
subtitle: "Proposal"
author: 
  - name: "Lean Mean Learning Machines"
    affiliations:
      - name: "School of Information, University of Arizona"
description: "Project description"
format:
  html:
    code-tools: true
    code-overflow: wrap
    code-line-numbers: true
    embed-resources: true
editor: visual
code-annotations: hover
execute:
  warning: false
jupyter: python3
---

```{python}
#| label: load-pkgs
#| message: false
import pandas as pd
import numpy as np
import seaborn as sns
```

## Introduction and data

```{python}
car_recalls = pd.read_csv("./data/Recalls_Data.csv")
```

### Identify the source of the data.

This data was collected by manufacturers who are required to report to National Highway Traffic Safety Administration (NHTSA) whenever they find a safety defect in their products. The safety guidelines of a product must align with the National Traffic and Motor Safety Act.

This dataset contains `{python} len(car_recalls.columns)` columns, primarily consisting of categorical data such as manufacturer, components affected, recall type, etc. There are two numerical data variables - number of potentially affected products and completion rates, if available.

## Research Question

Our target population can range anywhere from consumers of vehicles, vehicle components, or vehicle manufacturers themselves, as this data can be used to compare manufacturers, vehicles, and components with each other. This information can be useful for manufacturers to promote competition and production of better and more reliable products within this industry. It can also be useful to consumers so they can build more of an understanding for the most reliable vehicle and vehicle products that they can purchase from.

Potential research questions based on the data set:

1.  Over the past 10 years, what is the trend of number of recalls? Overall? Over select manufacturers? Over component type?
    i)  For overall number of recalls, our hypothesis is that number of overall recalls have decreased
    ii) For select manufacturers, we can select a few manufacturers to hone in on (maybe based on other data indicating high/low number of vehicle sales), and compare number of recalls. Our hypothesis is that the proportion of sales to recalls are congruent between high/low number of vehicle sales over the past 10 years.
    iii) For component type, we can select certain components such as components specifically designed for passenger safety and hypothesize that recalls had decreased over the past 10 years
    iv) **What's involved:** These research questions will involve quantitative data like number of recalls, number of potentially affected vehicles. It will also include categorical data such as manufacturers and component types. It will also deal with periodical data.
2.  What products tend to be up for recalls?
    i)  Our hypothesis is that throughout the past 10 or more years, there have been more electrical recalls due to increase in hybrid vehicles.
    ii) **What's involved:** This research question will deal with quantitative data such as number of recalls. It will also have categorical data such as recall types and component types.
3.  Upon the recalls, what is the percent of completion rate?
    i)  Our hypothesis is that over the years, the completion rate overall has been increasing
    ii) **What's involved:** This research question will deal with quantitative data such as completion rates, number of recalls. It will also deal with periodical data.

## Glimpse of data

```{python}
car_recalls.info()
```

```{python}
car_recalls.head()
```

## Analysis plan

Relative to the research questions stated above, here are the analysis plans for each of the questions:

-   1i) The variables involved would be number of recalls, number of vehicles potentially affected, and the dates of the report by year. We can make various analysis on this over a periodical graph indicating the trend of these numbers overtime.

-   1ii) The variables involved would be the number of recalls, number of vehicles potentially affected, the categorical data of component type, possibly the categorical data of recall type, and the dates of the report by year. We can also make a periodical graph indicating trends overtime, and then group by and discuss about a select recall/component type.

-   1iii) The variables involved would be the number of recalls, number of vehicles potentially affected, the categorical manufacturer data, the categorical data of component type, possibly the categorical data of recall type, and the dates of the report by year. With this, we can make a periodical graph differentiating the trends over year by manufacturer and broken down further into component and recall type.

-   2i) The variables involved would be the number of recalls and the categorical data of recall type, component type, and the date of the report. We can test this hypothesis by comparing the number of recalls of electrical recalls over time

-   3i) The variables involved would be the completion rate, number of recalls, and the date of the report. We can test his hypothesis by mapping out trends in the completion rate over a period of time and seeing if there is a strong pattern amongst the trend.